### ISSUE TITLE
I've read it! But don't understand the tasks.

### ISSUE THREAD

**Issue by AidenWard13** [meisl/logicly#7]
Finally i've finished. This tutorial was amazing. Understanding all the ways to use the grid to accomplish simple combinations for outputs. and reusing other logical combinations again.

I don't know what you mean by "with a performance analysis".
I don't know where to start in finding out if a NAND could be put in good use.

And i don't understand what you mean by
"3. Convert BCD inputs up to 19 (0x13): 5 bits in, 5 bits out." [EDIT: now task 1.b)]
up to 19?
0x13?

**Comment by meisl** [comment]
@AidenWard13 Thank you!

This part of task 1 [EDIT: the one about NAND, now 3] is hard. In fact I haven't found something myself. But that doesn't mean there is none...

As for task 3 [EDIT: about making logicly circuitsm now 1.b]: 19 is in decimal, 0x13 is the same number in hexadecimal (base 16; it's written like this in C-like languages). So as inputs you have one complete BCD digit for the ones plus one extra bit for the tens. From the 0x13 one can immediately see that this makes the output 5 bits wide as well.

**Comment by meisl** [comment]
Hmm, it looks like you've seen e3d5f8b9f8052486581314b3ec422f9dad99e09b from yesterday.
So that solved the Q3-simplification question mentioned in #2, right?

**Comment by AidenWard13** [comment]
Yes, I saw the update. I made this issue right after reading the then fully explained tutorial.

I don't know why you felt the need to state the numbers in hex. I understand hex, the decimal suggestion was all you needed. If it's a task, i should know how to put the number in decimal and get the correct binary out. All your tasks are "up to" some number. So that'd just make task 6 [EDIT: converter in logicly, now 1.e)] into task 2 [EDIT: now 1.a)] wouldn't it? Task 6 specifies "2 BCD digits". are 19, 39, 79 not 2 digit numbers? Without a doubt anyone would've had to ask what you're talking about. I'd have just wrote, Task 2: Convert 9, 19, 39, 79 and 99 (or all digits upto 99) from bcd to binary. Extra points for telling me how many bits are in the bcd/binary, and what the hex version of the numbers are.


It's not a hard thing to do really...
1001 1001 (8 bit bcd) -> 1100011 (7 bit binary)

Of course within logicly, you'd keep shifting the groups of 4 bits through the logic.

I think Mission Accomplished here now.
You have taught me well...

I could go do this on the double dabble logic. which is just bcd x2. the bits coming in are binary, which means current value x2 + binary digit. just to keep the binary incoming value in bcd. so the truth table to go for this time is just if >4 + 3. and on that truth table combinations 10-15 are don't cares, since a bcd will only validly be 0-9. it's like the same thing except the bit shifts in on the right. and that bit itself is the 1 of the bcd which is being looped into at the same time as the other 3 bcd bits.

but again, the problem is that for this serial version to work, it's got to be timed perfectly. we already have it at 3 ticks, the lowest logically can go is 2. so if we do manage, we'd might have to add some buffers. but still, we may be able to beat the 13 gates we have for the decoding/encoding of if>4+3 so far. and even if it took 13 gates (which it probably wont), performing faster is a benefit in of itself anyway. even if it is just 1 tick per bit faster. lol (so for an 80bit value, it'd be 80 ticks faster)

i'll go give it a go. ;)

**Comment by meisl** [comment]
@AidenWard13 Please write shorter comments. This is about the tasks of chapter 1, part 1 - nothing else.

If you've got ideas as to how to apply it to Binary-to-BCD now, that's totally great 👍 - but *please make an issue, one thing at a time*.
Really, too many issues hardly ever become a problem. But too long comments addressing all kinds of things are a problem right now.

I hope you're not too offended by my insisting on this. Really, I like what you wrote (and how you're writing it now), if only you could give this more organized way a try. It works pretty well for a lot people, particularly in programming ;)

Will answer to actual topic at hand later.

**Comment by meisl** [comment]
**How the tasks are given**
You really got me into thinking about that - thanks!
In order to keep this short (and to live up to my own standards), I'll just give an "executive summary". I've got a rationale ready for each point. Particularly for why I want the reader to do one more input bit at each step. So if you want...

- *Repetiveness* - agreed, that is indeed annoying.
- *"It's really 2 tasks, one of which just has variations"* - agreed.
- *Why stop at 99?* - you didn't ask that, anyways...
- *Hexadecimal* - agreed.
- *"2 BCD digits"* - agreed.
- *"Extra points for telling me how many bits..."* - agreed (-> additional task, + add "(*)"-ed tasks).

Finally, this my thinking resulted in 15898dd8b696648e960575dd0a5b0ba9f6bb1192 and c1f485660e881ed68a6085f47b257afad8a2834e. Or just click [here](https://github.com/meisl/logicly/blob/master/1_1_BCD-to-bin_Basic.md) and hit `Ctrl-End`.

What do you think of it now?

**Comment by meisl** [comment]
Looks resolved now to me - closing.

---
@AidenWard13 You can still comment on this issue, even if closed. Also, issues can be re-opened anytime if need be.
